application: blingpenn
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: client/dist/styles

- url: /images
  static_dir: client/dist/images

- url: /scripts
  static_dir: client/dist/scripts

- url: /.*
  script: blingnews.application

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^client
